var categories = ["Subject", "Keyword", "GER", "Title", "Units", "Quarter"];

var subjectCodes = [
  'EARTHSCI', 'EARTHSYS', 'EEES', 'ENERGY', 'ENVRES', 'EESS', 'GES', 'GEOPHYS', 'ENVRINST', 'EDUC', 'AA',
  'BIOE', 'CHEMENG', 'CEE', 'CME', 'CS', 'EE', 'ENGR', 'MS&E', 'MATSCI', 'ME', 'SCCM', 'AFRICAAM', 'AMELANG',
  'AFRICAST', 'AMSTUD', 'ANTHRO', 'APPPHYS', 'ARCHLGY', 'ARTHIST', 'ARTSTUDI', 'ASNAMST', 'ASNLANG', 'ASTRNMY',
  'ATHLETIC', 'BIO', 'BIOPHYS', 'CATLANG', 'CHEM', 'CHICANST', 'CHINGEN', 'CHINLANG', 'CHINLIT', 'CLASSART',
  'CLASSGEN', 'CLASSGRK', 'CLASSHIS', 'CLASSLAT', 'COMM', 'COMPLIT', 'CSRE', 'DANCE', 'DLCL', 'DRAMA', 'EASTASN',
  'ECON', 'ENGLISH', 'EFSLANG', 'ETHICSOC', 'FEMST', 'FILMPROD', 'FILMSTUD', 'FRENGEN', 'FRENLANG', 'FRENLIT',
  'GERGEN', 'GERLANG', 'GERLIT', 'HISTORY', 'HPS', 'HUMBIO', 'HUMSCI', 'ILAC', 'IBERLANG', 'IIS', 'HUMNTIES',
  'IPS', 'INTNLREL', 'ITALGEN', 'ITALLANG', 'ITALLIT', 'JAPANGEN', 'JAPANLNG', 'JAPANLIT', 'JEWISHST', 'KORGEN',
  'KORLANG', 'LATINAM', 'LINGUIST', 'MCS', 'MATH', 'MEDVLST', 'MTL', 'MUSIC', 'NATIVEAM', 'PHIL', 'PHYSICS',
  'POLISCI', 'PORTLANG', 'PSYCH', 'PUBLPOL', 'RELIGST', 'REES', 'STS', 'SLAVGEN', 'SLAVLANG', 'SLAVLIT', 'SOC',
  'SPANLANG', 'ILAC', 'SPECLANG', 'STATS', 'SYMSYS', 'TIBETLNG', 'URBANST', 'ACCT', 'MGTECON', 'FINANCE',
  'GSBGEN', 'HRMGT', 'MKTG', 'OIT', 'OB', 'POLECON', 'STRAMGT', 'LAW', 'LAWGEN', 'ANES', 'BIOC', 'BIOMEDIN',
  'CBIO', 'CTS', 'CSB', 'COMPMED', 'DERM', 'DBIO', 'FAMMED', 'GENE', 'HRP', 'IMMUNOL', 'MED', 'INDE', 'MI',
  'MCP', 'NBIO', 'NENS', 'NEPR', 'NSUR', 'OBGYN', 'OPHT', 'ORTHO', 'OTOHNS', 'PATH', 'PEDS', 'PSYC', 'RADO',
  'RAD', 'STEMREM', 'SBIO', 'SURG', 'UROL', 'CTL', 'IHUM', 'PWR', 'MLA'
];

var gers = ["DB:Hum", "DB:Math", "DB:SocSci", "DB:EngrAppSci", "DB:NatSci", "EC:EthicReas", "EC:GlobalCom",
  "EC:AmerCul", "EC:Gender", "Language", "Writing 1", "Writing 2", "Writing SLE", 'WAY-All', 'WAY-AQR', 'WAY-CE',
  'WAY-ED', 'WAY-ER', 'WAY-FR', 'WAY-SI', 'WAY-SMA'];